In [15]:
import pandas as pd
import numpy as np
import nltk
import spacy

In [19]:
import nltk
nltk.download()

showing info https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/index.xml


True

In [23]:
!python -m spacy download en_core_web_sm

                                              0.0/12.8 MB ? eta -:--:--
                                              0.0/12.8 MB ? eta -:--:--
                                             0.1/12.8 MB 656.4 kB/s eta 0:00:20
                                             0.1/12.8 MB 656.4 kB/s eta 0:00:20
                                             0.1/12.8 MB 602.4 kB/s eta 0:00:22
                                             0.1/12.8 MB 602.4 kB/s eta 0:00:22
                                             0.2/12.8 MB 510.2 kB/s eta 0:00:25
                                             0.3/12.8 MB 862.0 kB/s eta 0:00:15
     -                                        0.4/12.8 MB 1.0 MB/s eta 0:00:13
     -                                        0.5/12.8 MB 1.2 MB/s eta 0:00:11
     -                                        0.5/12.8 MB 1.2 MB/s eta 0:00:11
     --                                       0.7/12.8 MB 1.3 MB/s eta 0:00:10
     ---                                      1.0/12.8 MB 1.

In [3]:
data = pd.read_csv(r"C:\Users\yasar\OneDrive\Desktop\Deep learning\Fake news classification\WELFake_Dataset.csv")
data

Unnamed: 0                                              title  \
0               0  LAW ENFORCEMENT ON HIGH ALERT Following Threat...   
1               1                                                NaN   
2               2  UNBELIEVABLE! OBAMA’S ATTORNEY GENERAL SAYS MO...   
3               3  Bobby Jindal, raised Hindu, uses story of Chri...   
4               4  SATAN 2: Russia unvelis an image of its terrif...   
...           ...                                                ...   
72129       72129  Russians steal research on Trump in hack of U....   
72130       72130   WATCH: Giuliani Demands That Democrats Apolog...   
72131       72131  Migrants Refuse To Leave Train At Refugee Camp...   
72132       72132  Trump tussle gives unpopular Mexican leader mu...   
72133       72133  Goldman Sachs Endorses Hillary Clinton For Pre...   

                                                    text  label  
0      No comment is expected from Barack Obama Membe...      1  
1         Did they post their votes for Hillary already?      1  
2       Now, most of the demonstrators gathered last ...      1  
3      A dozen politically active pastors came here f...      0  
4      The RS-28 Sarmat missile, dubbed Satan 2, will...      1  
...                                                  ...    ...  
72129  WASHINGTON (Reuters) - Hackers believed to be ...      0  
72130  You know, because in fantasyland Republicans n...      1  
72131  Migrants Refuse To Leave Train At Refugee Camp...      0  
72132  MEXICO CITY (Reuters) - Donald Trump’s combati...      0  
72133  Goldman Sachs Endorses Hillary Clinton For Pre...      1  

[72134 rows x 4 columns]

In [7]:
data_title = data[['title', 'label']]

In [11]:
data_title.dropna(inplace = True)

C:\Users\yasar\AppData\Local\Temp\ipykernel_17416\2886711424.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_title.dropna(inplace = True)


In [17]:
data_title['title'][0]

'LAW ENFORCEMENT ON HIGH ALERT Following Threats Against Cops And Whites On 9-11By #BlackLivesMatter And #FYF911 Terrorists [VIDEO]'

In [24]:
data_title['title_cleaned'] = data_title['title'].apply(
    lambda x : " ".join(
        x.lower() for x in x.split()
    )
)

C:\Users\yasar\AppData\Local\Temp\ipykernel_17416\1458776051.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_title['title_cleaned'] = data_title['title'].apply(


In [25]:
data_title['title_cleaned']

0        law enforcement on high alert following threat...
2        unbelievable! obama’s attorney general says mo...
3        bobby jindal, raised hindu, uses story of chri...
4        satan 2: russia unvelis an image of its terrif...
5        about time! christian group sues amazon and sp...
                               ...                        
72129    russians steal research on trump in hack of u....
72130    watch: giuliani demands that democrats apologi...
72131    migrants refuse to leave train at refugee camp...
72132    trump tussle gives unpopular mexican leader mu...
72133    goldman sachs endorses hillary clinton for pre...
Name: title_cleaned, Length: 71576, dtype: object

In [26]:
data_title['title_cleaned'] = data_title['title_cleaned'].str.replace('[^\w\s]', '')
data_title['title_cleaned']

C:\Users\yasar\AppData\Local\Temp\ipykernel_17416\1989878809.py:1: FutureWarning: The default value of regex will change from True to False in a future version.
  data_title['title_cleaned'] = data_title['title_cleaned'].str.replace('[^\w\s]', '')
C:\Users\yasar\AppData\Local\Temp\ipykernel_17416\1989878809.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_title['title_cleaned'] = data_title['title_cleaned'].str.replace('[^\w\s]', '')


0        law enforcement on high alert following threat...
2        unbelievable obamas attorney general says most...
3        bobby jindal raised hindu uses story of christ...
4        satan 2 russia unvelis an image of its terrify...
5        about time christian group sues amazon and spl...
                               ...                        
72129    russians steal research on trump in hack of us...
72130    watch giuliani demands that democrats apologiz...
72131    migrants refuse to leave train at refugee camp...
72132    trump tussle gives unpopular mexican leader mu...
72133    goldman sachs endorses hillary clinton for pre...
Name: title_cleaned, Length: 71576, dtype: object

In [28]:
from nltk.corpus import stopwords
stop = stopwords.words('english')
data_title['title_cleaned'] = data_title['title_cleaned'].apply(
    lambda x : " ".join(
        x for x in x.split() if x not in stop
    )
)

data_title['title_cleaned']

C:\Users\yasar\AppData\Local\Temp\ipykernel_17416\3572837628.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_title['title_cleaned'] = data_title['title_cleaned'].apply(


0        law enforcement high alert following threats c...
2        unbelievable obamas attorney general says char...
3        bobby jindal raised hindu uses story christian...
4        satan 2 russia unvelis image terrifying new su...
5        time christian group sues amazon splc designat...
                               ...                        
72129    russians steal research trump hack us democrat...
72130    watch giuliani demands democrats apologize tru...
72131     migrants refuse leave train refugee camp hungary
72132    trump tussle gives unpopular mexican leader mu...
72133     goldman sachs endorses hillary clinton president
Name: title_cleaned, Length: 71576, dtype: object

In [31]:
data_title = data_title.reset_index()

In [32]:
tokenized = []
for i in range(len(data_title['title_cleaned'])):
    tokenized.append(nltk.word_tokenize(data_title['title_cleaned'][i]))
    
tokenized

[['law',
  'enforcement',
  'high',
  'alert',
  'following',
  'threats',
  'cops',
  'whites',
  '911by',
  'blacklivesmatter',
  'fyf911',
  'terrorists',
  'video'],
 ['unbelievable',
  'obamas',
  'attorney',
  'general',
  'says',
  'charlotte',
  'rioters',
  'peaceful',
  'protestersin',
  'home',
  'state',
  'north',
  'carolina',
  'video'],
 ['bobby',
  'jindal',
  'raised',
  'hindu',
  'uses',
  'story',
  'christian',
  'conversion',
  'woo',
  'evangelicals',
  'potential',
  '2016',
  'bid'],
 ['satan',
  '2',
  'russia',
  'unvelis',
  'image',
  'terrifying',
  'new',
  'supernuke',
  'western',
  'world',
  'takes',
  'notice'],
 ['time',
  'christian',
  'group',
  'sues',
  'amazon',
  'splc',
  'designation',
  'hate',
  'group'],
 ['dr',
  'ben',
  'carson',
  'targeted',
  'irs',
  'never',
  'audit',
  'spoke',
  'national',
  'prayer',
  'breakfast'],
 ['house',
  'intel',
  'chair',
  'trumprussia',
  'fake',
  'story',
  'evidence',
  'anything',
  'video']

In [33]:
data_title['title_cleaned'] = tokenized

In [71]:
data_title['title_cleaned'] =  data_title['title_cleaned'].apply(lambda x : ' '.join(i for i in x))

In [72]:
data_title

index                                              title  label  \
0          0  LAW ENFORCEMENT ON HIGH ALERT Following Threat...      1   
1          2  UNBELIEVABLE! OBAMA’S ATTORNEY GENERAL SAYS MO...      1   
2          3  Bobby Jindal, raised Hindu, uses story of Chri...      0   
3          4  SATAN 2: Russia unvelis an image of its terrif...      1   
4          5  About Time! Christian Group Sues Amazon and SP...      1   
...      ...                                                ...    ...   
71571  72129  Russians steal research on Trump in hack of U....      0   
71572  72130   WATCH: Giuliani Demands That Democrats Apolog...      1   
71573  72131  Migrants Refuse To Leave Train At Refugee Camp...      0   
71574  72132  Trump tussle gives unpopular Mexican leader mu...      0   
71575  72133  Goldman Sachs Endorses Hillary Clinton For Pre...      1   

                                           title_cleaned  
0      law enforcement high alert following threats c...  
1      unbelievable obamas attorney general says char...  
2      bobby jindal raised hindu uses story christian...  
3      satan 2 russia unvelis image terrifying new su...  
4      time christian group sues amazon splc designat...  
...                                                  ...  
71571  russians steal research trump hack us democrat...  
71572  watch giuliani demands democrats apologize tru...  
71573   migrants refuse leave train refugee camp hungary  
71574  trump tussle gives unpopular mexican leader mu...  
71575   goldman sachs endorses hillary clinton president  

[71576 rows x 4 columns]

In [73]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(data_title['title_cleaned'],
                                                    data_title['label'], 
                                                    test_size = 0.2)

In [74]:
X_train.shape, y_train.shape

((57260,), (57260,))

In [75]:
X_test.shape, y_test.shape

((14316,), (14316,))

In [76]:
from sklearn.feature_extraction.text import CountVectorizer
V = CountVectorizer()
cv = V.fit_transform(X_train)

In [77]:
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()
model.fit(cv, y_train)

MultinomialNB()

In [78]:
X_test_cv = V.transform(X_test)
from sklearn.metrics import classification_report
y_pred = model.predict(X_test_cv)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.88      0.89      0.88      7021
           1       0.89      0.88      0.89      7295

    accuracy                           0.89     14316
   macro avg       0.89      0.89      0.89     14316
weighted avg       0.89      0.89      0.89     14316



RNN

In [98]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import SimpleRNN, LSTM, GRU
from tensorflow.keras.layers import Dense

In [80]:
voc_size = 5000

In [105]:
messages = data_title['title_cleaned'].copy()
messages = messages.reset_index()

In [114]:
y = data_title['label']

In [107]:
corpus = []
for i in range(messages.shape[0]):
    corpus.append(messages['title_cleaned'][i])

In [143]:
def word_embeddings(corpus):
    onehot_repr = [one_hot(words, voc_size) for words in corpus]
    sent_length = 50
    embedded_docs = pad_sequences(onehot_repr, padding = 'pre', maxlen = sent_length)
    return embedded_docs

In [145]:
embedded_docs = word_embeddings(corpus)

In [151]:
embedding_vector_features = 40
model = Sequential()
model.add(Embedding(voc_size, embedding_vector_features, input_length = sent_length))
model.add(LSTM(150))
model.add(Dense(1, activation = 'sigmoid'))
model.compile(loss = 'binary_crossentropy', optimizer = 'adam', metrics = ['accuracy'])
model.summary()

Model: "sequential_5"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_5 (Embedding)     (None, 50, 40)            200000    
                                                                 
 gru (GRU)                   (None, 100)               42600     
                                                                 
 dense_5 (Dense)             (None, 1)                 101       
                                                                 
Total params: 242701 (948.05 KB)
Trainable params: 242701 (948.05 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [152]:
len(embedded_docs), y.shape

(71576, (71576,))

In [153]:
X_final = np.array(embedded_docs)
y_final = np.array(y)

In [154]:
X_final.shape, y_final.shape

((71576, 50), (71576,))

In [155]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_final, y_final, test_size = 0.2, 
                                                    random_state = 42)

In [156]:
model.fit(X_train, y_train, validation_data = (X_test, y_test), epochs = 10, batch_size = 64)

Epoch 1/10
895/895 [==============================] - 33s 34ms/step - loss: 0.3172 - accuracy: 0.8570 - val_loss: 0.2721 - val_accuracy: 0.8799
Epoch 2/10
895/895 [==============================] - 29s 33ms/step - loss: 0.2252 - accuracy: 0.9065 - val_loss: 0.2707 - val_accuracy: 0.8867
Epoch 3/10
895/895 [==============================] - 29s 32ms/step - loss: 0.1920 - accuracy: 0.9229 - val_loss: 0.2812 - val_accuracy: 0.8853
Epoch 4/10
895/895 [==============================] - 29s 32ms/step - loss: 0.1682 - accuracy: 0.9338 - val_loss: 0.2987 - val_accuracy: 0.8834
Epoch 5/10
895/895 [==============================] - 30s 33ms/step - loss: 0.1463 - accuracy: 0.9432 - val_loss: 0.3075 - val_accuracy: 0.8829
Epoch 6/10
895/895 [==============================] - 30s 33ms/step - loss: 0.1223 - accuracy: 0.9548 - val_loss: 0.3516 - val_accuracy: 0.8842
Epoch 7/10
895/895 [==============================] - 29s 33ms/step - loss: 0.0985 - accuracy: 0.9640 - val_loss: 0.3885 - val_accuracy:

In [157]:
y_pred = model.predict(X_test)
y_pred = np.where(y_pred > 0.5, 1, 0)

448/448 [==============================] - 5s 9ms/step


In [158]:
y_pred

array([[0],
       [1],
       [1],
       ...,
       [1],
       [1],
       [1]])

In [159]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)

array([[6035,  981],
       [ 751, 6549]], dtype=int64)

In [160]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

0.8790164850516904

In [162]:
X_test[0], y_pred[0]

(array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0, 2783, 3457,  369,
        1920, 4363,  749, 2821,  379, 3336]),
 array([0]))

In [174]:
data_title['title_cleaned'][71571], data_title['label'][71571]

('russians steal research trump hack us democratic party', 0)

In [195]:
data_title['title_cleaned'][71574], data_title['label'][71574]

('trump tussle gives unpopular mexican leader muchneeded shot arm', 0)

In [196]:
embed = word_embeddings(['trump tussle gives unpopular mexican leader muchneeded shot arm'])

In [197]:
pred = model.predict(embed)

1/1 [==============================] - 0s 32ms/step


In [198]:
pred

array([[0.00130394]], dtype=float32)